# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: lambdaServer

frameworkVersion: ">=1.16.0 <2.0.0"

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-2
  role: arn:aws:iam::198095930852:role/lambdaServer-dev-us-east-2-lambdaRole
      

environment:
  SLS_DEBUG: true

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    pythonBin: C:\Users\matth\AppData\Local\Programs\Python\Python37\python
    usePipenv: true

functions:
  new_user:
    handler: handler.new_user
    timeout: 30
    events:
      - http:
          path: /users/register
          method: post
          cors: 
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Access-Control-Allow-Origin
              - Access-Control-Allow-Headers
              - Access-Control-Allow-Methods

  new_device:
    handler: handler.new_device
    timeout: 30
    events:
      - http:
          path: /devices
          method: post
          cors: 
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Access-Control-Allow-Origin
              - Access-Control-Allow-Headers
              - Access-Control-Allow-Methods
  login_user:
    handler: handler.login_user
    timeout: 30
    events:
      - http:
          path: /users/login
          method: get
          cors: 
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Access-Control-Allow-Origin
              - Access-Control-Allow-Headers
              - Access-Control-Allow-Methods
  delete_user:
    handler: handler.delete_user
    timeout: 30
    events:
      - http:
          path: /users/remove
          method: delete
          cors: 
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Access-Control-Allow-Origin
              - Access-Control-Allow-Headers
              - Access-Control-Allow-Methods
  search_devices:
    handler: handler.find_device_by_code
    timeout: 30
    events:
      - http:
          path: /connect
          method: get
          cors: 
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Access-Control-Allow-Origin
              - Access-Control-Allow-Headers
              - Access-Control-Allow-Methods
  get_user_devices:
    handler: handler.get_devices_by_owner
    timeout: 30
    events:
      - http:
          path: /devices
          method: get
          cors: 
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Access-Control-Allow-Origin
              - Access-Control-Allow-Headers
              - Access-Control-Allow-Methods
  remove_device:
    handler: handler.remove_device
    timeout: 30
    events:
      - http:
          path: /devices
          method: delete
          cors: 
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Access-Control-Allow-Origin
              - Access-Control-Allow-Headers
              - Access-Control-Allow-Methods

