interface IConnectionConstants
{
    GET_CONNECTION_REQUEST: string,
    GET_CONNECTION_SUCCESS: string,
    GET_CONNECTION_ERROR: string,
    CONNECT_SUCCESS: string,

    GET_PUBLIC_DEVICES_REQUEST: string,
    GET_PUBLIC_DEVICES_SUCCESS: string,
    GET_PUBLIC_DEVICES_ERROR: string,
}

export const connectionConstants: IConnectionConstants =
{
    GET_CONNECTION_REQUEST: 'GET_CONNECTION_REQUEST',
    GET_CONNECTION_SUCCESS: 'GET_CONNECTION_SUCCESS',
    GET_CONNECTION_ERROR: 'GET_CONNECTION_ERROR',
    CONNECT_SUCCESS: 'CONNECT_SUCCESS',

    GET_PUBLIC_DEVICES_REQUEST: 'GET_PUBLIC_DEVICES_REQUEST',
    GET_PUBLIC_DEVICES_SUCCESS: 'GET_PUBLIC_DEVICES_SUCCESS',
    GET_PUBLIC_DEVICES_ERROR: 'GET_PUBLIC_DEVICES_ERROR',
}