interface IDeviceConstants
{
    GET_DEVICES_REQUEST: string,
    GET_DEVICES_SUCCESS: string,
    GET_DEVICES_ERROR: string,

    GET_PUBLIC_DEVICES_REQUEST: string,
    GET_PUBLIC_DEVICES_SUCCESS: string,
    GET_PUBLIC_DEVICES_ERROR: string,

    ADD_DEVICE_REQUEST: string,
    ADD_DEVICE_SUCCESS: string,
    ADD_DEVICE_ERROR: string,
    
    REMOVE_DEVICE_REQUEST: string,
    REMOVE_DEVICE_SUCCESS: string,
    REMOVE_DEVICE_ERROR: string,

    GET_DEVICE_HEALTH_REQUEST: string,
    GET_DEVICE_HEALTH_SUCCESS: string,
    GET_DEVICE_HEALTH_ERROR: string,

    POST_UPDATE_DEVICE_REQUEST: string,
    POST_UPDATE_DEVICE_SUCCESS: string,
    POST_UPDATE_DEVICE_ERROR: string
}

export const deviceConstants: IDeviceConstants =
{
    GET_DEVICES_REQUEST: 'GET_DEVICES_REQUEST',
    GET_DEVICES_SUCCESS: 'GET_DEVICES_SUCCESS',
    GET_DEVICES_ERROR: 'GET_DEVICES_ERROR',

    GET_PUBLIC_DEVICES_REQUEST: 'GET_PUBLIC_DEVICES_REQUEST',
    GET_PUBLIC_DEVICES_SUCCESS: 'GET_PUBLIC_DEVICES_SUCCESS',
    GET_PUBLIC_DEVICES_ERROR: 'GET_PUBLIC_DEVICES_ERROR',

    ADD_DEVICE_REQUEST: 'ADD_DEVICES_REQUEST',
    ADD_DEVICE_SUCCESS: 'ADD_DEVICES_SUCCESS',
    ADD_DEVICE_ERROR: 'ADD_DEVICES_ERROR',

    REMOVE_DEVICE_REQUEST: 'REMOVE_DEVICES_REQUEST',
    REMOVE_DEVICE_SUCCESS: 'REMOVE_DEVICES_SUCCESS',
    REMOVE_DEVICE_ERROR: 'REMOVE_DEVICES_ERROR',

    GET_DEVICE_HEALTH_REQUEST: 'GET_DEVICE_HEALTH_REQUEST',
    GET_DEVICE_HEALTH_SUCCESS: 'GET_DEVICE_HEALTH_SUCCESS',
    GET_DEVICE_HEALTH_ERROR: 'GET_DEVICE_HEALTH_ERROR',

    POST_UPDATE_DEVICE_REQUEST: 'POST_UPDATE_DEVICE_REQUEST',
    POST_UPDATE_DEVICE_SUCCESS: 'POST_UPDATE_DEVICE_SUCCESS',
    POST_UPDATE_DEVICE_ERROR: 'POST_UPDATE_DEVICE_ERROR'
}