interface IOrderConstants
{
    GET_ACTIONS_REQUEST: string,
    GET_ACTIONS_SUCCESS: string,
    GET_ACTIONS_ERROR: string,

    GET_INFO_REQUEST: string,
    GET_INFO_SUCCESS: string,
    GET_INFO_ERROR: string,

    GET_PRICE_REQUEST: string,
    GET_PRICE_SUCCESS: string,
    GET_PRICE_ERROR: string,

    GET_CAN_ORDER_REQUEST: string,
    GET_CAN_ORDER_SUCCESS: string,
    GET_CAN_ORDER_ERROR: string
}

export const orderConstants: IOrderConstants =
{
    GET_ACTIONS_REQUEST: 'GET_ACTIONS_REQUEST',
    GET_ACTIONS_SUCCESS: 'GET_ACTIONS_SUCCESS',
    GET_ACTIONS_ERROR: 'GET_ACTIONS_ERROR',

    GET_INFO_REQUEST: 'GET_INFO_REQUEST',
    GET_INFO_SUCCESS: 'GET_INFO_SUCCESS',
    GET_INFO_ERROR: 'GET_INFO_ERROR',

    GET_PRICE_REQUEST: 'GET_PRICE_REQUEST',
    GET_PRICE_SUCCESS: 'GET_PRICE_SUCCESS',
    GET_PRICE_ERROR: 'GET_PRICE_ERROR',

    GET_CAN_ORDER_REQUEST: 'GET_CAN_ORDER_REQUEST',
    GET_CAN_ORDER_SUCCESS: 'GET_CAN_ORDER_SUCCESS',
    GET_CAN_ORDER_ERROR: 'GET_CAN_ORDER_ERROR'
}